baseURL = 'https://Ashfaaq98.github.io/'
languageCode = 'en-us'
title = 'Ashfaaq Farzaan'
theme = ["paper",'hugo-shortcodes']

# Main Menu Configuration


[[menu.main]]

  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]

  name = "About"
  url = "/about/"
  weight = 10 # 

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

#[[menu.main]]
 # name = "Blog"
  #url = "/blog/" 
  #weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 40



[params]
  # color style
  color = 'linen'                           

  # header social icons
  twitter = '@TaprobaneLinux'              
  github = 'Ashfaaq98'                 
  linkedin = 'Ashfaaq98'             
  huggingface = "your-hf-username"

  # home page profile
  avatar = 'my-portfolio/static/images/ashfaaq.png'                 
  name = 'Ashfaaq Farzaan'
  bio = 'test'

[params.HugoShortcodes.BuyMeACoffee]
  Slug        = "qaafhsa"
  Text        = "Buy me a coffee"
  ButtonColor = "ffdd00"
  FontColor   = "000000"


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon


