baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = "paper"

# Main Menu Configuration


[[menu.main]]

  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]

  name = "About"
  url = "/about/"
  weight = 10 # Lower weight appears first

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  name = "Blog"
  url = "/blog/" # Paper theme often defaults to 'posts' for blog section
  weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 40



[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID


  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'YOUR_NAME'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon


